288: Fix checkForLoading to account for three possible loading states
sundeck-io/OpsCenter pull request #296
Opened 2023-09-12 22:09 UTC by susannahmarcus

1) no loading spinner EVER
2) loading sipper immediately
3) short delay and then a loading spinner

-- disabled the reset test since it was timing out locally without throttling

2023-09-12 23:12 UTC, vqmarkman requested changes

2023-09-12 23:23 UTC, susannahmarcus commented on cypress/e2e/settings.spec.cy.js
> +  it.only("Menu: Settings. Tab: Reset. Validate that we can click 'Reload' button and no exception is thrown .", () => {
Oh, I missed that somehow... sorry, will take this out

2023-09-12 23:23 UTC, susannahmarcus commented on cypress/support/utils.js
> +      cy.get('div[data-baseweb="select"]').should("exist").click();
ah, sorry, that seems like it was a rebase error I didn't notice. Fixing now.

2023-09-12 23:35 UTC, vqmarkman submitted a review, later dismissed
ship it! Now let's see what falls out after these changes ...

2023-09-13 00:35 UTC, doronrosenberg approved these changes

2023-09-13 04:04 UTC, vqmarkman commented on cypress/support/utils.js
> +      clickCheck({ clickElem: 'div[data-baseweb="select"]', forceClick: true });
```suggestion
      cy.get('svg[title="open"]').should("exist").click();
```

2023-09-13 05:32 UTC, vqmarkman approved these changes

2023-09-13 05:33 UTC, merged